#======================#
#=== WORKSPACE INFO ===#

[workspace]
  members  = ["crates/*"]
  resolver = "2"

[workspace.package]
  edition = "2024"
  version = "0.1.0"

  #========================#
  #=== PACKAGE SETTINGS ===#

[profile.dev]
  debug     = 0
  opt-level = 0
  strip     = "debuginfo"

[profile.dev.package."*"]
  opt-level = 2

[profile.release]
  codegen-units = 1
  debug         = 0
  lto           = "thin"
  opt-level     = 3
  panic         = 'abort'
  strip         = true

  #===============================#
  #=== DEPENDENCIES & FEATURES ===#

[workspace.dependencies]
  # CRATES
  scaffolding_logs  = { path = "crates/logs", version = "0.1.0" }
  scaffolding_time  = { path = "crates/time", version = "0.1.0" }
  scaffolding_tokio = { path = "crates/tokio", version = "0.1.0" }

  # STANDARD
  chrono = { version = "*", features = ["serde"] }

  # NETWORK
  tokio      = { version = "*", features = ["macros", "rt", "signal"] }
  tokio-util = { version = "*" }

  # NETWORK
  reqwest = { version = "*" }

  # UTILITIES
  thiserror = { version = "*" }

  # SERIALIZATION
  bitcode = { version = "*" }
  serde   = { version = "*", features = ["derive"] }

  # TERMINAL LOGS
  indicatif          = { version = "*" }
  tracing            = { version = "*" }
  tracing-indicatif  = { version = "*" }
  tracing-subscriber = { version = "*", features = ["env-filter"] }
