#====================#
#=== PACKAGE INFO ===#

[package]
  edition.workspace = true
  name              = "scaffolding_logs"
  version.workspace = true

  #===============================#
  #=== DEPENDENCIES & FEATURES ===#

[dependencies]
  chrono             = { workspace = true }
  indicatif          = { workspace = true }
  tracing            = { workspace = true }
  tracing-indicatif  = { workspace = true }
  tracing-subscriber = { workspace = true }

  reqwest = { workspace = true, optional = true }

[features]
  reqwest = ["dep:reqwest"]
