#====================#
#=== PACKAGE INFO ===#

[package]
  edition.workspace = true
  name              = "scaffolding_time"
  version.workspace = true

  #===============================#
  #=== DEPENDENCIES & FEATURES ===#

[dependencies]

  bitcode   = { workspace = true }
  chrono    = { workspace = true, features = ["serde"] }
  serde     = { workspace = true }
  thiserror = { workspace = true }
